### ISSUE TITLE
Option to change main color sheme and maybe a dark-mode?

### ISSUE THREAD

**Issue by poVoq** [convos-chat/www.convos.chat#14]
Is there an easy way to change the main light-green color of the header and landing page?

An automatic dark-mode might be also cool.

Thanks!

**Comment by jhthorsen** [comment]
Is this a question for https://convos.chat/ or your own personal instance?

**Comment by poVoq** [comment]
My personal instance using the CMS function.

**Comment by jhthorsen** [comment]
Then you can use https://convos.chat/doc/config#convos_default_theme-and-convos_default_scheme

An automatic dark-mode will break the official website, so I'm not going to prioritize that. I welcome a PR though.
