### ISSUE TITLE
Document setting "listen" via environment variable.

### ISSUE THREAD

**Issue by beep-beep-beep-boop** [convos-chat/www.convos.chat#17]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to change the listen setting when convos is running in a container. I initially didn't think this was possible, but realized that the `MOJO_LISTEN` environment variable can be used for this.

**Describe the solution you'd like**

Documenting setting this, possibly in the docker section of the documentation. Although, I guess it could be useful even when not running it in a container. It might also be worthwhile to document listening via a unix socket. `http+unix://%2Ftmp%2Fmyapp.sock` is what it uses an example when you run it via command-line, but it's not mentioned in the docs. 

**Additional context**

The reason I want to do this is to make it listen on a unix socket mounted in a docker volume, so I can mount that in the reverse-proxy container. I'm using networking options that make sharing networks between these containers not workable, so I have to do it in a different way.

**Comment by jhthorsen** [comment]
I'm pretty sure this will be closed in #19.
